import json
import os
from pathlib import Path
from typing import Optional

from agents import function_tool


def _build_html_report(report_path: Path) -> Optional[str]:
    """Read the JSON report and build a nice HTML email body."""
    try:
        with open(report_path) as f:
            data = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return None

    opps = data.get("ranked_opportunities", [])
    if not opps:
        return None

    total = data.get("total_results", "?")
    queries = data.get("queries_executed", "?")
    candidate = data.get("candidate_name", "Candidate")

    tier_icons = {"TOP PICKS": "🔥", "GOOD FITS": "✅", "WORTH EXPLORING": "📌"}
    tier_colors = {
        "TOP PICKS": "#FEF3C7",
        "GOOD FITS": "#D1FAE5",
        "WORTH EXPLORING": "#E0E7FF",
    }

    cards_html = ""
    for tier in ["TOP PICKS", "GOOD FITS", "WORTH EXPLORING"]:
        items = [o for o in opps if o.get("tier") == tier]
        if not items:
            continue
        icon = tier_icons.get(tier, "")
        color = tier_colors.get(tier, "#F1F5F9")
        cards_html += f"""
        <tr><td colspan="2" style="padding:20px 0 4px 0;font-size:16px;font-weight:700;color:#0F172A">{icon} {tier} ({len(items)})</td></tr>"""
        for item in items:
            title = item.get("title", "Untitled")
            company = item.get("company", "")
            company_str = f" &mdash; {company}" if company else ""
            score = item.get("score", "?")
            snippet = (item.get("snippet") or item.get("description", ""))[:200]
            url = item.get("apply_url") or item.get("source_url", "#")
            reasons = item.get("match_reasons", [])
            concerns = item.get("concerns", [])
            reasons_html = ""
            if reasons:
                reasons_html = (
                    "<div style='margin-top:6px;font-size:12px;color:#64748B'>"
                    + "".join(f"&bull; {r}<br>" for r in reasons)
                    + "</div>"
                )
            concerns_html = ""
            if concerns:
                concerns_html = (
                    "<div style='margin-top:4px;font-size:12px;color:#DC2626'>⚠️ "
                    + "; ".join(concerns)
                    + "</div>"
                )

            cards_html += f"""
        <tr><td colspan="2" style="padding:0 0 10px 0">
          <table width="100%" cellpadding="12" cellspacing="0" style="background:{color};border-radius:8px;border:1px solid #E2E8F0">
            <tr>
              <td style="font-size:14px;font-weight:600"><a href="{url}" style="color:#4F46E5;text-decoration:none">{title}{company_str}</a></td>
              <td width="60" align="center" style="font-size:15px;font-weight:700;color:#3730A3;white-space:nowrap">{score}/10</td>
            </tr>
            <tr><td colspan="2" style="padding:0 12px 8px 12px;font-size:13px;color:#64748B">{snippet}</td></tr>
            {reasons_html}
            {concerns_html}
          </table>
        </td></tr>"""

    html = f"""<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 0; background: #F1F5F9; }}
</style></head>
<body style="background:#F1F5F9;padding:24px">
  <table width="600" align="center" cellpadding="0" cellspacing="0" style="background:#FFFFFF;border-radius:12px;box-shadow:0 1px 3px rgba(0,0,0,.06)">
    <tr>
      <td style="background:linear-gradient(135deg,#3730A3,#4F46E5);padding:24px;border-radius:12px 12px 0 0;text-align:center">
        <h1 style="color:#FFFFFF;margin:0;font-size:22px;font-weight:800">EU Job Hunter Report</h1>
        <p style="color:rgba(255,255,255,.8);margin:4px 0 0 0;font-size:13px">{candidate} — {total} opportunities | {queries} queries</p>
      </td>
    </tr>
    <tr><td style="padding:20px">
      <table width="100%" cellpadding="0" cellspacing="0">
        {cards_html}
      </table>
    </td></tr>
    <tr><td style="padding:16px 20px;text-align:center;font-size:11px;color:#94A3B8;border-top:1px solid #E2E8F0">
      Generated by <strong>EU Job Hunter</strong> &middot; Crawl4AI + OpenRouter
    </td></tr>
  </table>
</body>
</html>"""
    return html


def send_report_email(
    subject: str,
    report_path: str,
    from_email: str | None = None,
    to_email: str | None = None,
) -> dict:
    """Send a formatted HTML report via SendGrid.

    Args:
        subject: Email subject line
        report_path: Path to the JSON report file on disk
        from_email: Override SENDGRID_FROM_EMAIL env var
        to_email: Override SENDGRID_TO_EMAIL env var

    Returns:
        dict with status and message
    """
    html_body = _build_html_report(Path(report_path))
    if not html_body:
        print(
            "  [WARN] Could not build HTML from report — file missing, invalid JSON, or no opportunities"
        )
        return {"status": "error", "message": "Could not build HTML from report"}

    api_key = os.environ.get("SENDGRID_API_KEY")
    from_email = from_email or os.environ.get("SENDGRID_FROM_EMAIL")
    to_email = to_email or os.environ.get("SENDGRID_TO_EMAIL")

    if not all([api_key, from_email, to_email]):
        print(
            "  [WARN] Missing SendGrid env vars: SENDGRID_API_KEY, SENDGRID_FROM_EMAIL, SENDGRID_TO_EMAIL"
        )
        return {
            "status": "error",
            "message": "SENDGRID_API_KEY, SENDGRID_FROM_EMAIL, SENDGRID_TO_EMAIL must be set",
        }

    try:
        import sendgrid
        from sendgrid.helpers.mail import Email, Mail, Content, To

        sg = sendgrid.SendGridAPIClient(api_key=api_key)
        mail = Mail(
            from_email=Email(from_email),
            to_emails=To(to_email),
            subject=subject,
            html_content=Content("text/html", html_body),
        )
        response = sg.client.mail.send.post(request_body=mail.get())
        print(f"  [OK] Email sent! Status: {response.status_code}")
        return {"status": "success", "status_code": response.status_code}
    except Exception as e:
        print(f"  [WARN] Email failed: {e}")
        return {"status": "error", "message": str(e)}


send_report_email_tool = function_tool(send_report_email)
